---
collections:
  - name: containers.podman
  - name: community.general
  - name: ansible.posix
  - name: amazon.aws
  - source: https://github.com/pumphouse-p/ansible-collection-cicd.git
    type: git
