---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9@sha256:5bb1f3c8151ab53642c46b6293030addffe3b5a99b7fdd8e32987b6ace6ae538

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_files:
  - dest: rpms
    src: openshift-clients-4.13.0-202311151332.p0.gc7c6eb2.assembly.stream.el9.x86_64.rpm

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base:
    - RUN /usr/bin/python3 -m pip install --upgrade pip setuptools
    - COPY _build/rpms/*.rpm /tmp/openshift-clients.rpm
    - RUN microdnf install bash-completion
    - RUN rpm -ivh /tmp/openshift-clients.rpm
  append_final:
    - ENV HELM_VERSION=3.13.2
    - RUN microdnf install tar xz && curl -sL -o helm.tar.gz https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz && tar xf helm.tar.gz linux-amd64/helm && chmod +x linux-amd64/helm && mv linux-amd64/helm /usr/bin && microdnf clean all && rm -rf helm.tar.gz linux-amd64