---
collections:
  - name: amazon.aws
  - name: community.aws
  - name: servicenow.itsm
  - name: community.general
  - name: containers.podman
  - name: google.cloud
  - name: community.google
  - name: azure.azcollection
  - name: openstack.cloud
  - name: community.digitalocean
  - name: vmware.vmware_rest
  - name: community.vmware
    version: 3.9.0
