---
collections:
  - name: amazon.aws
    version: 7.4.0
  - name: community.aws
    version: 7.1.0
  - name: servicenow.itsm
    version: 2.4.0
  - name: community.general
    version: 8.4.0
  - name: containers.podman
    version: 1.12.0
  - name: google.cloud
    version: 1.3.0
  - name: azure.azcollection
    version: 2.2.0
  - name: openstack.cloud
    version: 2.2.0
  - name: vmware.vmware_rest
    version: 4.7.0
  - name: community.vmware
    version: 5.6.0
