---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9@sha256:aa68fc3237438e1d841596c8297bd53d036d3d2fe67b631c9bc979c7eed3c6eb

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
