---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:1.0.0' 

dependencies:
  galaxy:
    collections:
      - name: amazon.aws
        version: 10.1.2
      - name: servicenow.itsm
        version: 2.13.0
      - name: azure.azcollection
        version: 3.9.0
  python:
    - pysnow
    - requests
    - boto3
    - botocore
    - urllib3

options:
  package_manager_path: /usr/bin/microdnf
