---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:1.0.0'

dependencies:
  galaxy:
    collections:
      - name: amazon.aws
        version: 10.1.2
      - name: community.aws
        version: 10.0.0
      - name: servicenow.itsm
        version: 2.13.0
      - name: community.general
        version: 11.4.0
      - name: google.cloud
        version: 1.9.0
      - name: cloud.terraform
        version: 4.0.0
      - name: hashicorp.terraform
        version: 1.1.0
      - name: ansible.scm
        version: 3.0.0
  python:
    - botocore
    - boto3
    - boto
    - pysnow
    - requests
    - pydantic
  system:
    - git [platform:rpm]

additional_build_steps:
  prepend_galaxy:
    - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub,galaxy
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://console.redhat.com/api/automation-hub/content/published/
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    - ENV ANSIBLE_GALAXY_SERVER_GALAXY_URL=https://galaxy.ansible.com
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
  append_final:
    - RUN microdnf install -y yum-utils
    - RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - RUN microdnf install -y terraform
    - RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - COPY azure-cli.repo /etc/yum.repos.d/azure-cli.repo
    - RUN microdnf install -y azure-cli

options:
  package_manager_path: /usr/bin/microdnf
