---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9@sha256:5bb1f3c8151ab53642c46b6293030addffe3b5a99b7fdd8e32987b6ace6ae538

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  append_final:
    - RUN microdnf install -y yum-utils
    - RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - RUN microdnf install -y terraform
    - RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - COPY azure-cli.repo /etc/yum.repos.d/azure-cli.repo
    - RUN microdnf install -y azure-cli

options:
  package_manager_path: /usr/bin/microdnf
