---
collections:
  - name: amazon.aws
    version: 6.2.0
  - name: community.aws
    version: 6.1.0
  - name: servicenow.itsm
    version: 2.2.0
  - name: community.general
    version: 7.2.0
  - name: google.cloud
    version: 1.1.2
  - name: cloud.terraform
    version: 1.1.1
  - name: ansible.scm
    version: 1.1.0
