---
collections:
  - name: amazon.aws
    version: 3.1.1
  - name: community.aws
    version: 2.1.0
  - name: servicenow.itsm
    version: 1.3.3
  - name: community.general
    version: 4.2.0
  - name: containers.podman
    version: 1.9.3
