---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/de-minimal-rhel9:latest

dependencies:
  galaxy:
    collections:
      - name: ansible.eda
        version: 2.10.0
      - name: dynatrace.event_driven_ansible
        version: 1.2.3
      - name: kentik.ansible_eda
        version: 1.0.7
      - name: crowdstrike.falcon
        version: 4.8.1
      - name: redhat.insights_eda
        version: 1.2.3
      - name: ibm.turbonomic_eda
        version: 1.0.2
  python:
    - six
    - psutil
    - aiohttp
  system:
    - iputils [platform:rpm]
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python3.11-devel [platform:rpm]

additional_build_steps:
  prepend_galaxy:
    - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub,galaxy
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://console.redhat.com/api/automation-hub/content/published/
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    - ENV ANSIBLE_GALAXY_SERVER_GALAXY_URL=https://galaxy.ansible.com
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
  prepend_base:
    - RUN $PYCMD -m pip install --upgrade pip setuptools
    - RUN $PYCMD -m pip install --upgrade --ignore-installed typing-extensions

options:
  package_manager_path: /usr/bin/microdnf
