---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:1.0.0' 

dependencies:
  galaxy:
    collections:
      - name: containers.podman
      - name: community.general
  python:
    - docker
    - python-jenkins
  system:
    - git [platform:rpm]
