---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:1.0.0' 

dependencies:
  system:
    - git [platform:rpm]
  galaxy:
    collections:
      - name: amazon.aws
        version: 10.1.2
      - name: community.aws
        version: 10.0.0
      - name: servicenow.itsm
        version: 2.13.0
      - name: community.general
        version: 11.4.0
      - name: containers.podman
        version: 1.18.0
      - name: ansible.posix
        version: 2.1.0
    roles:
      - name: geerlingguy.certbot
  python:
    - botocore
    - boto3
    - boto
    - pysnow

additional_build_steps:
  prepend_galaxy:
    - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub,galaxy
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://console.redhat.com/api/automation-hub/content/published/
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    - ENV ANSIBLE_GALAXY_SERVER_GALAXY_URL=https://galaxy.ansible.com
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN

options:
  package_manager_path: /usr/bin/microdnf
