---
collections:
  - name: amazon.aws
  - name: community.aws
  - name: servicenow.itsm
  - name: community.general
  - name: containers.podman
  - name: ansible.posix

roles:
  - name: geerlingguy.certbot
