---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8@sha256:35513a35612bdb1317c950bd3ad9fdc45d88cea3229007740146c470657f9ee7

dependencies:
  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf
