---
collections:
  - name: infra.aap_utilities
    version: 2.3.0
  - name: infra.controller_configuration
    version: 2.6.0
  - name: infra.ah_configuration
    version: 2.0.4
  - name: infra.ee_utilities
    version: 3.1.3
  - name: awx.awx
    version: 23.8.1
  - name: cloud.terraform
    version: 2.0.0
