collections:
  - name: redhat_cop.aap_utilities
    version: 2.2.1
  - name: redhat_cop.controller_configuration
    version: 2.2.5
  - name: redhat_cop.ah_configuration
    version: 0.9.1
  - name: redhat_cop.ee_utilities
    version: 1.0.1
  - name: awx.awx