collections:
  - name: redhat_cop.aap_utilities
    version: 2.2.4
  - name: redhat_cop.controller_configuration
    version: 2.3.1
  - name: redhat_cop.ah_configuration
    version: 1.1.1
  - name: redhat_cop.ee_utilities
    version: 2.0.7
  - name: awx.awx
