---
collections:
  - name: infra.aap_utilities
    version: 2.2.4
  - name: infra.controller_configuration
    version: 2.4.0
  - name: infra.ah_configuration
    version: 1.1.1
  - name: infra.ee_utilities
    version: 3.0.0
  - name: awx.awx
    version: 4.4.0
