---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:1.0.0'

dependencies:
  galaxy:
    collections:
      - name: microsoft.sql
        version: 2.5.2
      - name: chocolatey.chocolatey
        version: 1.5.3
      - name: ansible.windows
        version: 3.2.0
      - name: community.windows
        version: 3.0.1
      - name: microsoft.ad
        version: 1.9.2
      - name: microsoft.iis
        version: 1.0.3
  python:
    - pypsrp
    - pywinrm
    - cryptography
    - requests
  system:
    - gcc [platform:rpm]
    - python-devel [platform:rpm]
    - krb5-devel [platform:rpm]
  python_interpreter:
    python_path: /usr/bin/python3.11

additional_build_steps:
  prepend_galaxy:
    - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub,galaxy
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://console.redhat.com/api/automation-hub/content/published/
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    - ENV ANSIBLE_GALAXY_SERVER_GALAXY_URL=https://galaxy.ansible.com
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN

options:
  package_manager_path: /usr/bin/microdnf
