name: Terraform EE build

on:
  push:
    branches:
      - main
    paths:
      - 'ee-terraform/**'

  workflow_dispatch:

jobs:
  call-deploy-workflow:
    uses: pumphouse-p/ansible-execution-environments/.github/workflows/build-and-push.yml@main
    with:
      EE_DIR_NAME: ee-terraform
      EE_IMAGE_TAG: latest
      REGISTRY_URL: quay.io
      REGISTRY_USERNAME: deparris
    secrets: inherit
